# Generated by Django 5.0.3 on 2024-03-22 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news_app', '0003_alter_image_news_alter_news_author_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='subtitle',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
