# Generated by Django 5.0.3 on 2024-03-26 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news_app', '0004_alter_news_subtitle'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='slug',
        ),
        migrations.AddField(
            model_name='news',
            name='favorite',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
